import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../models/appointment.dart';
import '../general/messenger.dart';
import 'auth_service.dart';

final scheduleServiceProvider = Provider<ScheduleService>((ref) {
  return ScheduleService(ref);
});

final appointmentsProvider = StreamProvider<List<Appointment>>((ref) {
  final scheduleService = ref.watch(scheduleServiceProvider);
  return scheduleService.streamAppointments();
});

class ScheduleService {
  final Ref _ref;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  ScheduleService(this._ref);

  CollectionReference<Appointment> _getAppointmentsCollection() {
    final user = _ref.read(userProvider);
    if (user == null) {
      throw Exception('User not logged in!');
    }
    return _firestore
        .collection('users')
        .doc(user.uid)
        .collection('appointments')
        .withConverter<Appointment>(
      fromFirestore: (snapshot, _) => Appointment.fromFirestore(snapshot),
      toFirestore: (appointment, _) => appointment.toMap(),
    );
  }

  Stream<List<Appointment>> streamAppointments() {
    return _getAppointmentsCollection().snapshots().map((snapshot) {
      return snapshot.docs.map((doc) => doc.data()).toList();
    });
  }

  Future<bool> addAppointment({
    required String title,
    required DateTime date,
    required TimeOfDay time,
  }) async {
    try {
      final fullDateTime = DateTime(
        date.year,
        date.month,
        date.day,
        time.hour,
        time.minute,
      );

      final newAppointment = Appointment(
        id: '', // ID will be generated by Firestore
        title: title,
        dateTime: fullDateTime,
      );

      await _getAppointmentsCollection().add(newAppointment);

      _ref.read(messengerProvider).showSuccess('Appointment added successfully!');
      return true;
    } catch (e) {
      _ref.read(messengerProvider).showError('Failed to add appointment: ${e.toString()}');
      return false;
    }
  }

}